# Generated by Django 4.1.1 on 2022-09-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
