# Generated by Django 4.1.1 on 2022-09-27 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userdb_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdb',
            options={'ordering': ['first_name']},
        ),
    ]
