# Generated by Django 4.1.1 on 2022-09-26 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
    ]
