# Generated by Django 4.1.1 on 2022-09-26 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='CourseDb',
        ),
    ]
