# Generated by Django 4.1.1 on 2022-09-26 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_rename_course_coursedb'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='coursedb',
            table='course_db',
        ),
    ]
